//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockReadabilityTest {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ClockReadabilityTest.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        public static string TestType {
            get {
                return ResourceManager.GetString("TestType", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        public static string ResultAnalog {
            get {
                return ResourceManager.GetString("ResultAnalog", resourceCulture);
            }
        }
        
        public static string Countdown {
            get {
                return ResourceManager.GetString("Countdown", resourceCulture);
            }
        }
        
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        public static string KeyHint {
            get {
                return ResourceManager.GetString("KeyHint", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string NumValues {
            get {
                return ResourceManager.GetString("NumValues", resourceCulture);
            }
        }
        
        public static string NumPairs {
            get {
                return ResourceManager.GetString("NumPairs", resourceCulture);
            }
        }
        
        public static string CountdownSeconds {
            get {
                return ResourceManager.GetString("CountdownSeconds", resourceCulture);
            }
        }
        
        public static string ChooseHintMultiple {
            get {
                return ResourceManager.GetString("ChooseHintMultiple", resourceCulture);
            }
        }
        
        public static string ChooseHintSingle {
            get {
                return ResourceManager.GetString("ChooseHintSingle", resourceCulture);
            }
        }
        
        public static string SpeedTextFormat {
            get {
                return ResourceManager.GetString("SpeedTextFormat", resourceCulture);
            }
        }
        
        public static string TimeTextFormat {
            get {
                return ResourceManager.GetString("TimeTextFormat", resourceCulture);
            }
        }
        
        public static string Round5 {
            get {
                return ResourceManager.GetString("Round5", resourceCulture);
            }
        }
        
        public static string ResultDigital {
            get {
                return ResourceManager.GetString("ResultDigital", resourceCulture);
            }
        }
        
        public static string TimeTextFormat2 {
            get {
                return ResourceManager.GetString("TimeTextFormat2", resourceCulture);
            }
        }
        
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
